from jwst.datamodels import ImageModel


class BadPixImageModel(ImageModel):
    """
    A data model for 2D images corrected from bad pixels.

    Inherits all parameters from default JWST images.

    Parameters
    ----------
    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/badpiximage.schema"

    def __init__(self, init=None, **kwargs):

        super(BadPixImageModel, self).__init__(init=init, **kwargs)

        # Implicitly create remaining array
        self.dq_mod = self.dq_mod
