from jwst.datamodels import CubeModel


class BadPixCubeModel(CubeModel):
    """
    A data model for 3D image cubes corrected from bad pixels.

    Inherits all parameters from default JWST cubes.

    Parameters
    ----------
    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/badpixcube.schema"

    def __init__(self, init=None, **kwargs):

        super(BadPixCubeModel, self).__init__(init=init, **kwargs)

        # Implicitly create remaining array
        self.dq_mod = self.dq_mod
