from jwst.datamodels import CubeModel


class KPFitsModel(CubeModel):
    """
    A data model for KPFITS files with extracted kernel phases.

    Inherits all properties from default JWST cubes,
    with additionaly KPI-specific data.

    Parameters
    __________
    aperture : numpy float64 table
        Aperture grid points (m) and transmission (fraction 0 <= t <= 1)

    uv_plane : numpy float64 table
        UV plane coordinates (m) and redunancy (number of baselines)

    ker_mat : numpy float32 array
        KPM matrix from Fourier to Kernel phase

    blm_mat : numpy float32 array
        Matrix mapping pupil phase to fourier phase

    kp_data : numpy float32 array
        Kernel phase data (rad)

    ker_sigm : numpy float32 array
        Kernel phase uncertainties (rad)

    ker_cov : numpy float32 array
        Kernel phase covariance (rad^2)

    cwavel: numpy float64 table
        Bandpass characteristics (central and bandwidth)

    detpa : numpy float32 array
        Detector position angle (deg E of N)

    cvis_data : numpy float32 array
        Complex visibility data (real, img)

    data_org : numpy float32 array
        Original science cube before pre-processing

    err_org : numpy float32 array
        Original error cube before pre-processing

    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step

    sgmask : numpy float32 array
        Super-Gaussian mask used for windowing
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/kpfits.schema"
