from jwst.datamodels import CubeModel


class RecenterCubeModel(CubeModel):
    """
    A data model for recentered science cube.

    Inherits all properties from default JWST cubes.

    Parameters
    __________
    data_org : numpy float32 array
        Original science cube before pre-processing

    err_org : numpy float32 array
        Original error cube before pre-processing

    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step

    imshift : numpy float64 table
        Table of shifts used to recenter image
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/recentercube.schema"
