from jwst.datamodels import ImageModel


class RecenterImageModel(ImageModel):
    """
:   A data model for recentered science image.

    Inherits all properties from default JWST images.

    Parameters
    __________
    data_org : numpy float32 array
        Original science image before pre-processing

    err_org : numpy float32 array
        Original error image before pre-processing

    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step

    imshift : numpy float64 table
        Table of shifts used to recenter image
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/recenterimage.schema"
