from jwst.datamodels import ImageModel


class WindowImageModel(ImageModel):
    """
    A data model for KPFITS files with extracted kernel phases.

    Inherits all properties from default JWST images,
    with additionaly KPI-specific data.

    Parameters
    __________
    data_org : numpy float32 array
        Original science image before pre-processing

    err_org : numpy float32 array
        Original error image before pre-processing

    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step

    sgmask : numpy float32 array
        Super-Gaussian mask used for windowing
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/windowimage.schema"
