from jwst.datamodels import CubeModel


class WindowCubeModel(CubeModel):
    """
    A data model for KPFITS files with extracted kernel phases.

    Inherits all properties from default JWST cubes,
    with additionaly KPI-specific data.

    Parameters
    __________
    data_org : numpy float32 array
        Original science cube before pre-processing

    err_org : numpy float32 array
        Original error cube before pre-processing

    dq_mod : numpy float32 array
        The bad pixel max generated by bad pixel correction step

    sgmask : numpy float32 array
        Super-Gaussian mask used for windowing
    """

    schema_url = "http://stsci.edu/schemas/jwst_kpi_datamodel/windowcube.schema"
